// $Header: /devl/xcs/repo/env/Databases/CAEInterfaces/xec_libs/data/unisims/PCIE_A1.v,v 1.3 2009/08/22 00:32:35 harikr Exp $
///////////////////////////////////////////////////////////////////////////////
// Copyright (c) 1995/2009 Xilinx, Inc.
// All Right Reserved.
///////////////////////////////////////////////////////////////////////////////
//   ____  ____
//  /   /\/   /
// /___/  \  /    Vendor : Xilinx
// \   \   \/     Version : 11.1i (L.11)
//  \   \         Description : Xilinx Formal Library Component
//  /   /
// /___/   /\     Filename : PCIE_A1.v
// \   \  /  \    Timestamp :
//  \___\/\___\
//
// Revision:
//    04/28/09 - Initial version.
// End Revision

`timescale 1 ps / 1 ps 

module PCIE_A1 (
  CFGBUSNUMBER,
  CFGCOMMANDBUSMASTERENABLE,
  CFGCOMMANDINTERRUPTDISABLE,
  CFGCOMMANDIOENABLE,
  CFGCOMMANDMEMENABLE,
  CFGCOMMANDSERREN,
  CFGDEVCONTROLAUXPOWEREN,
  CFGDEVCONTROLCORRERRREPORTINGEN,
  CFGDEVCONTROLENABLERO,
  CFGDEVCONTROLEXTTAGEN,
  CFGDEVCONTROLFATALERRREPORTINGEN,
  CFGDEVCONTROLMAXPAYLOAD,
  CFGDEVCONTROLMAXREADREQ,
  CFGDEVCONTROLNONFATALREPORTINGEN,
  CFGDEVCONTROLNOSNOOPEN,
  CFGDEVCONTROLPHANTOMEN,
  CFGDEVCONTROLURERRREPORTINGEN,
  CFGDEVICENUMBER,
  CFGDEVSTATUSCORRERRDETECTED,
  CFGDEVSTATUSFATALERRDETECTED,
  CFGDEVSTATUSNONFATALERRDETECTED,
  CFGDEVSTATUSURDETECTED,
  CFGDO,
  CFGERRCPLRDYN,
  CFGFUNCTIONNUMBER,
  CFGINTERRUPTDO,
  CFGINTERRUPTMMENABLE,
  CFGINTERRUPTMSIENABLE,
  CFGINTERRUPTRDYN,
  CFGLINKCONTOLRCB,
  CFGLINKCONTROLASPMCONTROL,
  CFGLINKCONTROLCOMMONCLOCK,
  CFGLINKCONTROLEXTENDEDSYNC,
  CFGLTSSMSTATE,
  CFGPCIELINKSTATEN,
  CFGRDWRDONEN,
  CFGTOTURNOFFN,
  DBGBADDLLPSTATUS,
  DBGBADTLPLCRC,
  DBGBADTLPSEQNUM,
  DBGBADTLPSTATUS,
  DBGDLPROTOCOLSTATUS,
  DBGFCPROTOCOLERRSTATUS,
  DBGMLFRMDLENGTH,
  DBGMLFRMDMPS,
  DBGMLFRMDTCVC,
  DBGMLFRMDTLPSTATUS,
  DBGMLFRMDUNRECTYPE,
  DBGPOISTLPSTATUS,
  DBGRCVROVERFLOWSTATUS,
  DBGREGDETECTEDCORRECTABLE,
  DBGREGDETECTEDFATAL,
  DBGREGDETECTEDNONFATAL,
  DBGREGDETECTEDUNSUPPORTED,
  DBGRPLYROLLOVERSTATUS,
  DBGRPLYTIMEOUTSTATUS,
  DBGURNOBARHIT,
  DBGURPOISCFGWR,
  DBGURSTATUS,
  DBGURUNSUPMSG,
  MIMRXRADDR,
  MIMRXREN,
  MIMRXWADDR,
  MIMRXWDATA,
  MIMRXWEN,
  MIMTXRADDR,
  MIMTXREN,
  MIMTXWADDR,
  MIMTXWDATA,
  MIMTXWEN,
  PIPEGTPOWERDOWNA,
  PIPEGTPOWERDOWNB,
  PIPEGTTXELECIDLEA,
  PIPEGTTXELECIDLEB,
  PIPERXPOLARITYA,
  PIPERXPOLARITYB,
  PIPERXRESETA,
  PIPERXRESETB,
  PIPETXCHARDISPMODEA,
  PIPETXCHARDISPMODEB,
  PIPETXCHARDISPVALA,
  PIPETXCHARDISPVALB,
  PIPETXCHARISKA,
  PIPETXCHARISKB,
  PIPETXDATAA,
  PIPETXDATAB,
  PIPETXRCVRDETA,
  PIPETXRCVRDETB,
  RECEIVEDHOTRESET,
  TRNFCCPLD,
  TRNFCCPLH,
  TRNFCNPD,
  TRNFCNPH,
  TRNFCPD,
  TRNFCPH,
  TRNLNKUPN,
  TRNRBARHITN,
  TRNRD,
  TRNREOFN,
  TRNRERRFWDN,
  TRNRSOFN,
  TRNRSRCDSCN,
  TRNRSRCRDYN,
  TRNTBUFAV,
  TRNTCFGREQN,
  TRNTDSTRDYN,
  TRNTERRDROPN,
  USERRSTN,
  CFGDEVID,
  CFGDSN,
  CFGDWADDR,
  CFGERRCORN,
  CFGERRCPLABORTN,
  CFGERRCPLTIMEOUTN,
  CFGERRECRCN,
  CFGERRLOCKEDN,
  CFGERRPOSTEDN,
  CFGERRTLPCPLHEADER,
  CFGERRURN,
  CFGINTERRUPTASSERTN,
  CFGINTERRUPTDI,
  CFGINTERRUPTN,
  CFGPMWAKEN,
  CFGRDENN,
  CFGREVID,
  CFGSUBSYSID,
  CFGSUBSYSVENID,
  CFGTRNPENDINGN,
  CFGTURNOFFOKN,
  CFGVENID,
  CLOCKLOCKED,
  MGTCLK,
  MIMRXRDATA,
  MIMTXRDATA,
  PIPEGTRESETDONEA,
  PIPEGTRESETDONEB,
  PIPEPHYSTATUSA,
  PIPEPHYSTATUSB,
  PIPERXCHARISKA,
  PIPERXCHARISKB,
  PIPERXDATAA,
  PIPERXDATAB,
  PIPERXENTERELECIDLEA,
  PIPERXENTERELECIDLEB,
  PIPERXSTATUSA,
  PIPERXSTATUSB,
  SYSRESETN,
  TRNFCSEL,
  TRNRDSTRDYN,
  TRNRNPOKN,
  TRNTCFGGNTN,
  TRNTD,
  TRNTEOFN,
  TRNTERRFWDN,
  TRNTSOFN,
  TRNTSRCDSCN,
  TRNTSRCRDYN,
  TRNTSTRN,
  USERCLK
);

  parameter [31:0] BAR0 = 32'h00000000;
  parameter [31:0] BAR1 = 32'h00000000;
  parameter [31:0] BAR2 = 32'h00000000;
  parameter [31:0] BAR3 = 32'h00000000;
  parameter [31:0] BAR4 = 32'h00000000;
  parameter [31:0] BAR5 = 32'h00000000;
  parameter [31:0] CARDBUS_CIS_POINTER = 32'h00000000;
  parameter [23:0] CLASS_CODE = 24'h000000;
  parameter integer DEV_CAP_ENDPOINT_L0S_LATENCY = 7;
  parameter integer DEV_CAP_ENDPOINT_L1_LATENCY = 7;
  parameter DEV_CAP_EXT_TAG_SUPPORTED = "FALSE";
  parameter integer DEV_CAP_MAX_PAYLOAD_SUPPORTED = 2;
  parameter integer DEV_CAP_PHANTOM_FUNCTIONS_SUPPORT = 0;
  parameter DEV_CAP_ROLE_BASED_ERROR = "TRUE";
  parameter DISABLE_BAR_FILTERING = "FALSE";
  parameter DISABLE_ID_CHECK = "FALSE";
  parameter DISABLE_SCRAMBLING = "FALSE";
  parameter ENABLE_RX_TD_ECRC_TRIM = "FALSE";
  parameter [21:0] EXPANSION_ROM = 22'h000000;
  parameter FAST_TRAIN = "FALSE";
  parameter integer GTP_SEL = 0;
  parameter integer LINK_CAP_ASPM_SUPPORT = 1;
  parameter integer LINK_CAP_L0S_EXIT_LATENCY = 7;
  parameter integer LINK_CAP_L1_EXIT_LATENCY = 7;
  parameter LINK_STATUS_SLOT_CLOCK_CONFIG = "FALSE";
  parameter [14:0] LL_ACK_TIMEOUT = 15'h0204;
  parameter LL_ACK_TIMEOUT_EN = "FALSE";
  parameter [14:0] LL_REPLAY_TIMEOUT = 15'h060D;
  parameter LL_REPLAY_TIMEOUT_EN = "FALSE";
  parameter integer MSI_CAP_MULTIMSGCAP = 0;
  parameter integer MSI_CAP_MULTIMSG_EXTENSION = 0;
  parameter [3:0] PCIE_CAP_CAPABILITY_VERSION = 4'h1;
  parameter [3:0] PCIE_CAP_DEVICE_PORT_TYPE = 4'h0;
  parameter [4:0] PCIE_CAP_INT_MSG_NUM = 5'b00000;
  parameter PCIE_CAP_SLOT_IMPLEMENTED = "FALSE";
  parameter [11:0] PCIE_GENERIC = 12'h000;
  parameter PLM_AUTO_CONFIG = "FALSE";
  parameter integer PM_CAP_AUXCURRENT = 0;
  parameter PM_CAP_D1SUPPORT = "TRUE";
  parameter PM_CAP_D2SUPPORT = "TRUE";
  parameter PM_CAP_DSI = "FALSE";
  parameter [4:0] PM_CAP_PMESUPPORT = 5'b01111;
  parameter PM_CAP_PME_CLOCK = "FALSE";
  parameter integer PM_CAP_VERSION = 3;
  parameter [7:0] PM_DATA0 = 8'h1E;
  parameter [7:0] PM_DATA1 = 8'h1E;
  parameter [7:0] PM_DATA2 = 8'h1E;
  parameter [7:0] PM_DATA3 = 8'h1E;
  parameter [7:0] PM_DATA4 = 8'h1E;
  parameter [7:0] PM_DATA5 = 8'h1E;
  parameter [7:0] PM_DATA6 = 8'h1E;
  parameter [7:0] PM_DATA7 = 8'h1E;
  parameter [1:0] PM_DATA_SCALE0 = 2'b01;
  parameter [1:0] PM_DATA_SCALE1 = 2'b01;
  parameter [1:0] PM_DATA_SCALE2 = 2'b01;
  parameter [1:0] PM_DATA_SCALE3 = 2'b01;
  parameter [1:0] PM_DATA_SCALE4 = 2'b01;
  parameter [1:0] PM_DATA_SCALE5 = 2'b01;
  parameter [1:0] PM_DATA_SCALE6 = 2'b01;
  parameter [1:0] PM_DATA_SCALE7 = 2'b01;
  parameter SIM_VERSION = "1.0";
  parameter SLOT_CAP_ATT_BUTTON_PRESENT = "FALSE";
  parameter SLOT_CAP_ATT_INDICATOR_PRESENT = "FALSE";
  parameter SLOT_CAP_POWER_INDICATOR_PRESENT = "FALSE";
  parameter integer TL_RX_RAM_RADDR_LATENCY = 1;
  parameter integer TL_RX_RAM_RDATA_LATENCY = 2;
  parameter integer TL_RX_RAM_WRITE_LATENCY = 0;
  parameter TL_TFC_DISABLE = "FALSE";
  parameter TL_TX_CHECKS_DISABLE = "FALSE";
  parameter integer TL_TX_RAM_RADDR_LATENCY = 0;
  parameter integer TL_TX_RAM_RDATA_LATENCY = 2;
  parameter USR_CFG = "FALSE";
  parameter USR_EXT_CFG = "FALSE";
  parameter VC0_CPL_INFINITE = "TRUE";
  parameter [11:0] VC0_RX_RAM_LIMIT = 12'h01E;
  parameter integer VC0_TOTAL_CREDITS_CD = 104;
  parameter integer VC0_TOTAL_CREDITS_CH = 36;
  parameter integer VC0_TOTAL_CREDITS_NPH = 8;
  parameter integer VC0_TOTAL_CREDITS_PD = 288;
  parameter integer VC0_TOTAL_CREDITS_PH = 32;
  parameter integer VC0_TX_LASTPACKET = 31;

  output CFGCOMMANDBUSMASTERENABLE;
  output CFGCOMMANDINTERRUPTDISABLE;
  output CFGCOMMANDIOENABLE;
  output CFGCOMMANDMEMENABLE;
  output CFGCOMMANDSERREN;
  output CFGDEVCONTROLAUXPOWEREN;
  output CFGDEVCONTROLCORRERRREPORTINGEN;
  output CFGDEVCONTROLENABLERO;
  output CFGDEVCONTROLEXTTAGEN;
  output CFGDEVCONTROLFATALERRREPORTINGEN;
  output CFGDEVCONTROLNONFATALREPORTINGEN;
  output CFGDEVCONTROLNOSNOOPEN;
  output CFGDEVCONTROLPHANTOMEN;
  output CFGDEVCONTROLURERRREPORTINGEN;
  output CFGDEVSTATUSCORRERRDETECTED;
  output CFGDEVSTATUSFATALERRDETECTED;
  output CFGDEVSTATUSNONFATALERRDETECTED;
  output CFGDEVSTATUSURDETECTED;
  output CFGERRCPLRDYN;
  output CFGINTERRUPTMSIENABLE;
  output CFGINTERRUPTRDYN;
  output CFGLINKCONTOLRCB;
  output CFGLINKCONTROLCOMMONCLOCK;
  output CFGLINKCONTROLEXTENDEDSYNC;
  output CFGRDWRDONEN;
  output CFGTOTURNOFFN;
  output DBGBADDLLPSTATUS;
  output DBGBADTLPLCRC;
  output DBGBADTLPSEQNUM;
  output DBGBADTLPSTATUS;
  output DBGDLPROTOCOLSTATUS;
  output DBGFCPROTOCOLERRSTATUS;
  output DBGMLFRMDLENGTH;
  output DBGMLFRMDMPS;
  output DBGMLFRMDTCVC;
  output DBGMLFRMDTLPSTATUS;
  output DBGMLFRMDUNRECTYPE;
  output DBGPOISTLPSTATUS;
  output DBGRCVROVERFLOWSTATUS;
  output DBGREGDETECTEDCORRECTABLE;
  output DBGREGDETECTEDFATAL;
  output DBGREGDETECTEDNONFATAL;
  output DBGREGDETECTEDUNSUPPORTED;
  output DBGRPLYROLLOVERSTATUS;
  output DBGRPLYTIMEOUTSTATUS;
  output DBGURNOBARHIT;
  output DBGURPOISCFGWR;
  output DBGURSTATUS;
  output DBGURUNSUPMSG;
  output MIMRXREN;
  output MIMRXWEN;
  output MIMTXREN;
  output MIMTXWEN;
  output PIPEGTTXELECIDLEA;
  output PIPEGTTXELECIDLEB;
  output PIPERXPOLARITYA;
  output PIPERXPOLARITYB;
  output PIPERXRESETA;
  output PIPERXRESETB;
  output PIPETXRCVRDETA;
  output PIPETXRCVRDETB;
  output RECEIVEDHOTRESET;
  output TRNLNKUPN;
  output TRNREOFN;
  output TRNRERRFWDN;
  output TRNRSOFN;
  output TRNRSRCDSCN;
  output TRNRSRCRDYN;
  output TRNTCFGREQN;
  output TRNTDSTRDYN;
  output TRNTERRDROPN;
  output USERRSTN;
  output [11:0] MIMRXRADDR;
  output [11:0] MIMRXWADDR;
  output [11:0] MIMTXRADDR;
  output [11:0] MIMTXWADDR;
  output [11:0] TRNFCCPLD;
  output [11:0] TRNFCNPD;
  output [11:0] TRNFCPD;
  output [15:0] PIPETXDATAA;
  output [15:0] PIPETXDATAB;
  output [1:0] CFGLINKCONTROLASPMCONTROL;
  output [1:0] PIPEGTPOWERDOWNA;
  output [1:0] PIPEGTPOWERDOWNB;
  output [1:0] PIPETXCHARDISPMODEA;
  output [1:0] PIPETXCHARDISPMODEB;
  output [1:0] PIPETXCHARDISPVALA;
  output [1:0] PIPETXCHARDISPVALB;
  output [1:0] PIPETXCHARISKA;
  output [1:0] PIPETXCHARISKB;
  output [2:0] CFGDEVCONTROLMAXPAYLOAD;
  output [2:0] CFGDEVCONTROLMAXREADREQ;
  output [2:0] CFGFUNCTIONNUMBER;
  output [2:0] CFGINTERRUPTMMENABLE;
  output [2:0] CFGPCIELINKSTATEN;
  output [31:0] CFGDO;
  output [31:0] TRNRD;
  output [34:0] MIMRXWDATA;
  output [35:0] MIMTXWDATA;
  output [4:0] CFGDEVICENUMBER;
  output [4:0] CFGLTSSMSTATE;
  output [5:0] TRNTBUFAV;
  output [6:0] TRNRBARHITN;
  output [7:0] CFGBUSNUMBER;
  output [7:0] CFGINTERRUPTDO;
  output [7:0] TRNFCCPLH;
  output [7:0] TRNFCNPH;
  output [7:0] TRNFCPH;

  input CFGERRCORN;
  input CFGERRCPLABORTN;
  input CFGERRCPLTIMEOUTN;
  input CFGERRECRCN;
  input CFGERRLOCKEDN;
  input CFGERRPOSTEDN;
  input CFGERRURN;
  input CFGINTERRUPTASSERTN;
  input CFGINTERRUPTN;
  input CFGPMWAKEN;
  input CFGRDENN;
  input CFGTRNPENDINGN;
  input CFGTURNOFFOKN;
  input CLOCKLOCKED;
  input MGTCLK;
  input PIPEGTRESETDONEA;
  input PIPEGTRESETDONEB;
  input PIPEPHYSTATUSA;
  input PIPEPHYSTATUSB;
  input PIPERXENTERELECIDLEA;
  input PIPERXENTERELECIDLEB;
  input SYSRESETN;
  input TRNRDSTRDYN;
  input TRNRNPOKN;
  input TRNTCFGGNTN;
  input TRNTEOFN;
  input TRNTERRFWDN;
  input TRNTSOFN;
  input TRNTSRCDSCN;
  input TRNTSRCRDYN;
  input TRNTSTRN;
  input USERCLK;
  input [15:0] CFGDEVID;
  input [15:0] CFGSUBSYSID;
  input [15:0] CFGSUBSYSVENID;
  input [15:0] CFGVENID;
  input [15:0] PIPERXDATAA;
  input [15:0] PIPERXDATAB;
  input [1:0] PIPERXCHARISKA;
  input [1:0] PIPERXCHARISKB;
  input [2:0] PIPERXSTATUSA;
  input [2:0] PIPERXSTATUSB;
  input [2:0] TRNFCSEL;
  input [31:0] TRNTD;
  input [34:0] MIMRXRDATA;
  input [35:0] MIMTXRDATA;
  input [47:0] CFGERRTLPCPLHEADER;
  input [63:0] CFGDSN;
  input [7:0] CFGINTERRUPTDI;
  input [7:0] CFGREVID;
  input [9:0] CFGDWADDR;

endmodule // PCIE_A1
